### ISSUE TITLE
Syncschema not syncing the updated local schema with remote schema in chewie-NS server

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/chewBBACA#125]
Dear chewBBACA team,

I tested the syncschema option and noticed the local schema is up to date. However, these alleles were not syncing with the remote schema in chewie-NS server (last update of remote schema is showing the date from last year) as below:

######################################################################################
(base) ubuntu@innuendo2-master-machine:/mnt/singularity_cache2$ **singularity exec -B $PWD ummidock-chewbbaca-2.8.5.img chewBBACA.py SyncSchema --schema-directory** /mnt/singularity_cache2/shared_files/chewbbaca_test_bala/yersinia/test_schema_yersinia_download/yenterocolitica_INNUENDO_wgMLST

chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - SyncSchema
==========================
Started at: 2022-04-07T09:44:26

Schema id: 1
Schema name: INNUENDO_wgMLST
Schema's species: Yersinia enterocolitica (id=7)
Last synced: 2021-05-31T16:47:32.442204

**Remote schema was last modified on: 2021-05-31T16:47:32.442204**

Remote schema has **not been updated** since last sync process. Local schema is up-to-date.
##########################################################################

Any suggestions on how to make this sync between local and remote schema will be very useful!

Best Regards,
Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

By default, the SyncSchema process allows users to retrieve novel alleles or simply synchronize allele identifiers that were added to the remote schemas. To submit novel alleles that have been identified in your local analyses, you must have permission to submit alleles. We do not provide this type of permissions to every registered user right from the start because it is important to perform allele calling with high quality data and based on the same parameters that were used to create the schema. Having this type of permission right from the start could more easily lead to the submission of problematic alleles that were identified in low quality assemblies simply because the option was easily available and users could inadvertently submit problematic alleles without giving it much thought.
Please send us an email to imm-bioinfo@medicina.ulisboa.pt if you want to have permission to submit alleles to remote schemas.

Rafael

**Comment by bala-ruokavirasto** [comment]
Dear Rafael,

Thanks for your reply! It is really good that you have this checkpoint/permission step so that people aware of the assembly quality and problematic alleles produced due to low quality assemblies.

Currently, our workflow frameworks handles this very nicely with the quast statistics and we have quality check points in the pipeline so that the assembly files does not goes into chewbbaca if the quality of the assembly is low or below the cutoff.

Do you have any specific recommendations/cutoff thresholds on some quast statistics on the assembly that we should follow before we input the assembly into the chewbbaca?

We want permission to submit and synchronize the local and remote schema in regular intervals. Do we need to apply for institutional login username and password for our purposes as the workflow is based in CSC, Finland and used by both THL and Ruokavirasto, Finland?

Kindly let us know!

Thanks in advance!

Best Regards,
Bala

**Comment by bala-ruokavirasto** [comment]
I really appreciate the chewbbaca team for their concern of maintaining the schema in chewieNS server without any direct submission of low quality reads or genomes or syncing them. So, i recommend to people having problem with syncschema to contact the team and they are helping to give some informed access so that you dont submit/sync your local to remote.

Some of the important things to consider are your WGS data is not contaminated (Confindr and Kraken2 might help to access this). Then, the quality of reads also needs to be checked. On top of that, the quality of assembly needs to be checked with quast statistics and compare the core genes of the assembled genomes.

It is important to check the above things on your data before you sync the locally identified allele variants to the remote schema in the chewie-NS server. If you are not sure, then it is better to not do the sync as it might mess up the allele variants.

Hope my comments are useful for the people trying to sync the schema!

Best Regards,
Bala
