### ISSUE TITLE
Error with AlleleCall

### ISSUE THREAD

**Issue by hkaspersen** [B-UMMI/chewBBACA#129]
Hello, and thank you for creating chewBBACA!
We are trying to run cgMLST version 2.8.5 on a few genomes of S. enterica, by using the cgMLST scheme from Enterobase.
We downloaded the scheme directly from enterobase: https://enterobase.warwick.ac.uk/schemes/Salmonella.cgMLSTv2/cgMLST_salmonella.tar

Further, we unpacked and unzipped all the fasta files, and downloaded the prodigal training file from https://github.com/B-UMMI/chewBBACA/blob/master/CHEWBBACA/prodigal_training_files/Salmonella_enterica.trn. Then we ran the PrepExternalSchema command:

```
chewBBACA.py PrepExternalSchema -i /path/to/downloaded/schema -o output --ptf  Salmonella_enterica.trn --cpu 4
```
This finished successfully (3000/3002 genes successful), but when we tried to run the AlleleCall we get an error. This is the command we ran:

```
chewBBACA.py AlleleCall -i $input_dir -g $schema_senterica -o $output_dir --cpu 16 --ptf $ptf
```
where `$ptf` is the same prodigal training file as we used on the prep schema command.

This is the error message we got:
```
Failed to predict genes for 13 genomes.
Info for failed cases stored in: /cluster/projects/nn9305k/db_flatfiles/chewbbaca_schemes/senterica_cgmlst_v2/prodigal_stderr.tsv
Please remove invalid inputs and try again.
```
In the `.tsv` file the following message is found:
```
Warning: user-specified translation table doesnot match the one in the specified training file! Error: training file did not read correctly!
```
We have checked that there are no duplicates in the input fasta files, that they are readable, and seem normal. Further, we have checked that it is using the correct prodigal training file. Note that we get this error regardless if we are using the `--ptf` option in the command or not. 

Any suggestions as to why we see this error?
Thanks in advance!

**Comment by rfm-targa** [comment]
Hello @hkaspersen,

Thank you for your interest in chewBBACA. I used equivalent commands with the schema and training file that you have linked but could not reproduce the warning. In my case, the `AlleleCall` process accepts the training file. This is the expected behaviour because the default value for the translation table used by the `PrepExternalSchema` process and the translation table used to create the training file are the same (translation table 11). It is possible that the AlleleCall process is failing due to other issue that is not being properly captured. I suggest that you retry the whole process and check all the values passed to the `PrepExternalSchema` and `AlleleCall` processes to make sure that they are valid. If the issue persists, and if possible, I suggest that you share with us the schema adapted by the `PrepExternalSchema` process and the dataset of 13 genome assemblies. We could then attempt to identify the cause of the warning and patch it to improve chewBBACA.

Rafael

**Comment by hkaspersen** [comment]
Hello again,
We managed to figure it out - the input file names contained "." which seem to affect the sample ID somehow. Also, the training file was incorrect. After these changes the program runs fine.

**Comment by ramirma** [comment]
Great to hear it worked out @hkaspersen. The limitation with the processing of the file names (periods are not recommended) is known. Thank you for getting back to us on this.
