### ISSUE TITLE
Error on line 435

### ISSUE THREAD

**Issue by abomba** [B-UMMI/chewBBACA#137]
Hi, 
I ran into a problem with allele calling while using cgMLST schema from [pubmlst](https://pubmlst.org/bigsdb?db=pubmlst_campylobacter_seqdef&page=schemeInfo&scheme_id=4). Error looks simillar to #91 but in my case BSR is calculated and errors appears only in some samples in specific loci.

e.g
```
chewBBACA version: 2.8.5
...
Processing CAMP1839.fasta. Start 09:22:01-17/08/2022 Locus 5 of 1343. Done 0%.Getting BSR at : 09:22:01-17/08/2022
Finished BSR at : 09:22:04-17/08/2022
starting allele call blast at: 09:22:04-17/08/2022
...
assemblies/Cj_0157.fasta
assemblies/Cj_0158.fasta
assemblies/Cj_0160.fasta
assemblies/Cj_0161.fasta
assemblies/Cj_0162.fasta
assemblies/Cj_0163.fasta
assemblies/Cj_0165.fasta
assemblies/Cj_0166.fasta
assemblies/Cj_0167.fasta
assemblies/Cj_0169.fasta
assemblies/Cj_0171.fasta
Blasting alleles on genome at : 09:22:04-17/08/2022
Blasted alleles on genome at : 09:22:05-17/08/2022
BSR : 0.9831081081081081
some error occurred
'109'
Error on line 435
assemblies/ERR4224360.fasta
assemblies/ERR4224362.fasta
assemblies/ERR4224363.fasta
...
```
Maybe is the same problem as #91  and i just misunderstand those logs, I will be grateful for your advice.

Best Regards,
Arek

**Comment by rfm-targa** [comment]
Hello @abomba,

Thank you for your interest in chewBBACA. The text that you shared does seem to indicate that it's a similar issue, but the full text printed by chewBBACA would help us to better understand the issue because it has more information. Do you still have the full text printed to stdout and the command used to run the AlleleCall process?
It would also be useful to have the list of commands you used to adapt the schema and a genome assembly that leads to the issue you described. This would allow us to test and find the exact cause.

Rafael

**Comment by abomba** [comment]
Hi, 
After your question about commands used to adapt schema I decide to readapt it because it was done 6 month ago and I didn't save any commands. To my surprise, newly adapted schema works on my dataset without any errors . At first glance all fasta files, permissions etc. in both schemas looks the same but  *_bsr.txt are diff. I dont know what was the problem but maybe you have some idea. To readapt schema i used  `chewBBACA.py PrepExternalSchema -i ../cjejuni_cgmlst/loci_fa/ -o schema --ptf ../cjejuni_cgmlst/Campylobacter_jejuni.trn --cpu 22`. I can't share genome assemblies and besides this, logs after my original dataset take up 300mb so I ran AlleleCall on 2 random genomes to recreate error. Logs and genomes attaching below.
[newschema.log](https://github.com/B-UMMI/chewBBACA/files/9372501/newschema.log)
[oldschema.log](https://github.com/B-UMMI/chewBBACA/files/9372502/oldschema.log)
[genomes.zip](https://github.com/B-UMMI/chewBBACA/files/9372509/genomes.zip)

Arek

**Comment by ramirma** [comment]
Thank you @abomba for having gotten back to us on this. Given that you were able to run the schema without problems we believe this may have been a problem of accessing some files in the original version. It is hard to replicate the error without full access to the schema and anyway this seems to have been an episodic problem rather than a more consistent chewBBACA error. I will close the issue but do not hesitate to get back to us if you run into further errors.

Mario
