### ISSUE TITLE
cgMLST for two species at the same time

### ISSUE THREAD

**Issue by ireneortega** [B-UMMI/chewBBACA#142]
I want to perform cgMLST on two Campylobacter species (C. jejuni and C. coli), but I am not sure how to do it.

I downloaded the Schema of PubMLST named [C. jejuni / C. coli cgMLST v1.0](https://pubmlst.org/bigsdb?db=pubmlst_campylobacter_seqdef&page=schemeInfo&scheme_id=4) and I want to adapt this external schema in chewBBACA. In the `chewBBACA.py PrepExternalSchema` command, the Prodigal training file is optional, but it is recommended to use it. In my case, I do not if I have to use. If yes, I can have a reference genome for each specie, but I don't know how to adapt the external schema becade the training file only refers to one reference genome. Should I run that command twice for each specie using two Prodigal training file (one for each specie)? But then how I just get one `cgMLST.tsv` file to later construct a minimum spanning tree or phylogenetic tree? I am not sure about the steps I have to make.

Then, for allele calling, do I need to use as input my genome assemblies of study? I am confused about using reference genomes first and then perform the allele calling in my genomes of interest as described [here](https://github.com/B-UMMI/chewBBACA_tutorial)

**Comment by ramirma** [comment]
If you want to use the same schema with both species and directly compare the results you have to use the same training file. Choose a reference genome of one of the species and create a training file. Then use the schema to do allele calling on all isolates of interest independently of the species. You can then construct a minimum-spanning tree with the calls in [PHYLOViZ](http://www.phyloviz.net/) (I would suggest that you use the beta [online version](https://online2.phyloviz.net/index))

**Comment by ireneortega** [comment]
Ok, I finally managed it following your instructions @ramirma Many thanks!

One last question: would it be valid to include a third species (C. lari) using the scheme defined for only two spcies (C. jejuni/C. coli)? I tried and got 779 loci out of 1343 of the PubMLST Schema for C. jejuni/C. coli, but I am worried if it is valid or I should create a new cgMLST schema por C. lari with ref genomes and therefore draw two separete minimum-spanning tree, one for C. jejuni/C. coli and another for C. lari.

**Comment by ramirma** [comment]
If you want to compare the three species you have to use the same schema. As you indicate this will result on calling a much reduced number of loci (only those that are common to the three species), but the profiles will be directly comparable. I know little of the biology of _Campylobacter _, but I presume from your comments that while _C. jejuni_ and _C. coli_ are closely related, _C. lari_ is more distantly related.

So the answer really boils down to what you want to compare. Since you already know that these are three species and you probably want to get discrimination within the each of the species, you would probably be better served by creating a schema for _C. lari_ that could would be more powerful at discriminating lineages within this species (it would probably have many more loci). However, creating a schema may be a lot of work (depending on how polished you want it to be) and the 779 loci may provide enough resolution for you to discriminate sufficiently within your collection. The allele calls performed by chewBBACA are valid, it just identifies fewer loci. It is really up to you.

I hope to have clarified your question.

Mario

**Comment by ireneortega** [comment]
@ramirma Absolutely yes, many thanks for your explanation. I can now work with certainty. In fact, on my previous [post](https://github.com/B-UMMI/chewBBACA/issues/28#issuecomment-1252039388), the phylogenetic tree based on cgMLST compared up to 5 different species using the schema created for just two of them.
