### ISSUE TITLE
No possibilty to turn off gene prediction completly

### ISSUE THREAD

**Issue by TorHou** [B-UMMI/chewBBACA#171]
Hi,

the software is really cool. Thank you very much for your efforts.

We have identified an issue with it, however. We want to use it on _M. Tuberculosis_ samples and we do have a cgMLST scheme that is [well established](https://www.cgmlst.org/ncs/schema/741110/). Now whenever we run chewBBACA.py AlleleCall there are a few genes out of the scheme which are missed completely (LNF: locus not found, from `loci_summary_stats.tsv`) for all samples that we try to run it on. When we mapped the alleles of the gene to our assemblies of the samples we see perfect matches, as in edit distance: 0.

We looked into this some more and found out, that in some cases Prodigal finds two separate ORFs where the gene should be (from the `cds_coordinates.tsv`). Now we will look into using some other gene prediction tools, but we would also like to know, is there a way to turn of the gene prediction completely? Because there is a perfect match and the cgMLST scheme is well established we are quite sure that the gene is correct and that Prodigal is wrong in its assessment that there are two different ORFs.

Kind regards and thank you for solving [my other issue](https://github.com/B-UMMI/chewBBACA/issues/163)
Torsten H.

**Comment by ramirma** [comment]
Dear Torsten,

Thank you for your kind words and continued interest in chewBBACA. The identification of ORFs from a genome is a crucial first step in chewBBACA and this is by design. This decision was based on the premise that ORF sizes could vary and we wanted chewBBACA to be able to accommodate this variation. We have therefore no option to bypass this step by simply looking for the exact same sequence in the genome as one of the alleles in the schema. 

You seem to have found a case in which prodigal consistently "makes a mistake" in identifying an ORF (for which I presume there is other evidence supporting that the ORF in the schema is indeed a coding sequence). I presume you have created a prodigal training file from a high quality genome. You could try to use a different high quality genome to generate the training file, but I doubt this would solve this problem. Although this is a problem related to prodigal it could be interesting to see what could be the characteristics of this region that lead to this behavior.

We have plans to allow using [Pyrodigal ](https://github.com/althonos/pyrodigal/) for ORF finding in a future version of chewBBACA but I am not sure if that would solve your problem. You may want to try it on your sequences. If it works correctly, you could use the produced ORFs with chewBBACA, since the only current solution for your problem is to feed a set of ORFs to chewBBACA which do not have that problem you describe.

I am sorry we cannot provide a better solution and I hope to have clarified your question.

Best Regards,

Mario

**Comment by TorHou** [comment]
Thank you for your answer. I will have to look into Prodigal and other gene prediction tools more.
