### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by karlkashofer** [B-UMMI/chewBBACA#184]
I just wanted to use AlleleCallEvaluator but it was not available, took me a while to realize that there is now a 3.3.0 release.

The docs for AlleleCallEvaluator are great, but it would be good to update the "Installation" section of the docs accordingly:

`Install the latest released version using [conda](https://anaconda.org/bioconda/chewbbaca):
conda create -c bioconda -c conda-forge -n chewie "chewbbaca=3.2.0"`

Thanks,
KK

**Comment by rfm-targa** [comment]
Greetings @karlkashofer,

I apologize for the discrepancy between the documentation and the latest version that can be installed through PyPI or Conda (version 3.2.0). We are working on releasing version 3.3.0 soon. The documentation already includes information about the AlleleCallEvaluator module, which will be available when version 3.3.0 is out. I will let you know when it is available for installation through PyPI or Conda.

Best regards,

Rafael

**Comment by karlkashofer** [comment]
Dear Rafael !
Thanks for the quick answer and explanation. No worries, i found your excellent Dockerscript and use that now. 
Its really clean and efficient and works well on our 99core cluster nodes !
Cheers,
KK

**Comment by rfm-targa** [comment]
Hello @karlkashofer,

Thank you for your kind words. The Dockerfile is also something new in v3.3.0. Glad that you found it helpful. Let me know if you find any issues while executing chewBBACA through Docker.

Best regards,

Rafael

**Comment by rfm-targa** [comment]
Dear @karlkashofer,

chewBBACA v3.3.0 is now available to install through [pip](https://pypi.org/project/chewBBACA/) and [conda](https://anaconda.org/bioconda/chewbbaca). This version includes the AlleleCallEvaluator module. We've also updated the installation instructions and the [Dockerfile](https://github.com/B-UMMI/chewBBACA/blob/master/Dockerfile) included in the repo. The Dockerfile now installs the latest stable version/release instead of cloning and installing what's in the master branch.
If you install chewBBACA v3.3.0 through conda, you must install FastTree separately. The conda recipe does not include FastTree as a dependency. We've created a [PR](https://github.com/bioconda/bioconda-recipes/pull/43646) to fix the recipe, and that issue should be resolved soon.
I'll close this issue, but let us know about any issues you might find with the latest version.

Kind regards,

Rafael
