### ISSUE TITLE
About using the external schema in the Schema Create process

### ISSUE THREAD

**Issue by huizhen2014** [B-UMMI/chewBBACA#19]
Hi, on my practice following the Wiki recipe, I had noticed It allowed us to use the external schema, such as them from Ridom cgMLST, BIGSdb or Enterobase. So I want to confirm with you that in the ridom seqsphere website I found a link which could enable us to down load the cgMLST schema:https://www.cgmlst.org/ncs/schema/3953420/locus/
So could you kindly tell me whether the link, Download alleles as fasta, in the page could allow us to get what we could use in the chewBBAC PrepExternalSchema process, and what the difference between the training schema by CreateSchema and the external schema like from Ridom?
Thank you!

**Comment by mickaelsilva** [comment]
Different schema sources are created with different rules, for instance some may allow the sequences not to be a coding sequence. Since our allele call engine only works with coding sequences, the PrepExternalSchema processes cleans the locus for that kind of choices made a priori, meaning it removes the sequences that are not a coding sequence.
PrepExternalSchema accepts a single folder with multifasta files (extension .fasta), meaning you can use any kind of schema you want, but take that previous point into consideration. Also the fastas should present a standard header for each sequence  with the allele index separated with a _ , e.g. 

```
>alleleA_1
AGTCGATGCATGCATAGCTAG
>alleleB_2
ATGCGTAGCTAGCTAGCATG
 ```
