### ISSUE TITLE
external scheme creation problem

### ISSUE THREAD

**Issue by aslangabriel** [B-UMMI/chewBBACA#24]
I tried to creat salmonella scheme by myself and entered the command line as follows"chewBBACA.py CreateSchema -i cgMLST/ -o Salmonellascheme --cpu 8 --ptf training/Salmonella_enterica.trn", but it prompted error message "chewbbaca scheme creation error:BLAST Database error: No alias or index file found for protein database [/home/qifeng/temp/protogenome1/blastdbs/protogenome1_proteins_db] in search path [/home/qifeng::" halfway. How can I fix it.
P.S. I create an environment and install chewbbaca via conda

**Comment by mickaelsilva** [comment]
-i option needs to be a folder with genomes only inside. genomes must be fasta files.

**Comment by aslangabriel** [comment]
I downloaded all the cgMLST allele sequences from enterobacteriaceae  and decompressed within this folder. I checked the help manual, should I use the prepareexternalscheme or place the trainning files in -i folder

**Comment by mickaelsilva** [comment]
"CreateSchema" is to create a new schema based on a set of genomes, if you already have a schema use the "prepareexternalscheme" function. You can't create a schema with chewbbaca based on a set of sequences you have, since it needs to run prodigal to find the sequences.

if you want you can try one of the schemas we have working for salmonella enterica, see https://zenodo.org/record/1323684
