### ISSUE TITLE
Invalid start byte error

### ISSUE THREAD

**Issue by aaron-bio** [B-UMMI/chewBBACA#29]
Hi,

I keep getting the following error whenever I run chewBBACA, it doesn't seem to interrupt the program but should I be concerned? 

'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

**System info:**
Operating system: MacOSX 10.12.6
Python 3.7.2

Thanks.

**Comment by mickaelsilva** [comment]
Can you check on your results_alleles.tsv files if there is any "ERROR" result?

**Comment by aaron-bio** [comment]
Just checked the results_alleles.tsv. No "ERROR" result in it.

**Comment by jacarrico** [comment]
Sorry for the delay in follow-up but it has been easter holiday season.
Does this happen everytime you invoke `chewBBACA.py` ? Or with a specific dataset?

**Comment by aaron-bio** [comment]
Well, it usually happens when I invoke the SchemaEvaluator module of chewBBACA.py. I tried it again with the tutorial dataset provided at https://github.com/B-UMMI/chewBBACA_tutorial. Still got the exact same error message and the output html file is a bit wonky. The graphs in the html file are not showing up as expected.

**Comment by jacarrico** [comment]
What version of chewBBACA are you running?

**Comment by aaron-bio** [comment]
I am using version 2.0.16

**Comment by mickaelsilva** [comment]
Regarding the graphs not showing up, have you tried opening them with firefox?

**Comment by rfm-targa** [comment]
This issue has been observed when one of the input directories (input genomes or schema directory) have invalid file types that are not recognized by the process. The process expects FASTA files and this error will be displayed when it encounters a file that does not match that file format. This issue should be resolved in the latest version.

This issue has been inactive for a long time and will be closed. Feel free to reopen if it was not caused by what I described or if the issue seems to be affecting the results.
