### ISSUE TITLE
PrepExternalSchema enhancement request

### ISSUE THREAD

**Issue by eam12** [B-UMMI/chewBBACA#38]
When using the PrepExternalSchema command with an external database, it sometimes may take multiple hours or even days to run. It would be really nice to have a feature where if the command is interrupted for some reason or if a new loci is added later PrepExternalSchema could pick up where it left off. I am currently having that issue and now have to wait another 32 hours after only adding two new loci.

**Comment by rfm-targa** [comment]
Greetings,

First, I think we can make some changes to _PrepExternalSchema_ so that it runs considerably faster. After that, we can start exploring your suggestions and add an option to continue an interrupted process (just as AlleleCall has one).

Could you please tell us the total number of loci and the total number of alleles in the schema you are trying to adapt?

**Comment by eam12** [comment]
I'm using the Enterobase Salmonella cgMLST scheme which consists of 3002 loci and 4,718,005 alleles. I'm currently running _PrepExternalSchema_ on 14 cores/48 GB. It's been running for about 24 hours now and has completed 2387/3002 loci. Thank you!

**Comment by rfm-targa** [comment]
Hello,

We have released a new version (2.1.0) with a new implementation for the `PrepExternalSchema` process. It is considerably faster than the previous version and outputs new files with relevant information about the schema that was adapted and sequences that the process excluded and why they were excluded. The process has new options so that schemas can be adapted based on different BSR, minimum sequence length and genetic code parameters. It is also possible to add new genes or alleles to a gene in the schema with this new implementation. You can read more about the new implementation in the [Wiki, Section 1.4](https://github.com/B-UMMI/chewBBACA/wiki/1.-Schema-Creation#14-using-an-external-schema).
We used the new implementation to adapt the Enterobase Salmonella cgMLST schema with 3002 loci and >4M alleles in 30m37s (with 6 CPU threads and a maximum memory usage of 132MB).
We hope that it helps and appreciate any feedback that you can give us.
