### ISSUE TITLE
Question about cgMLST analysis

### ISSUE THREAD

**Issue by daniazi** [B-UMMI/chewBBACA#50]
Hi,
Before posting here I have been through the tutorial and the user guide but I think I missed the information which I need to perform cgMLST analysis for some isolates (targets). I want to be sure about how exactly the pipeline should be run in order to obtain cgMLST profile of target genomes. To create cgMLST schema we picked some complete reference genomes. Then I have executed following set of commands:

#Creating schema using Ref genomes
`chewBBACA.py CreateSchema -i $ccoli_ref_genomes -o ${out_ccoli}/1_seed_schema --ptf ${training}/c_coli.trn --cpu 24`

#Now allele calling from Ref genomes
`chewBBACA.py AlleleCall -i $ccoli_ref_genomes -g ${out_ccoli}/1_seed_schema/ -o ${out_ccoli}/2_wg_ref_allele --cpu 24 --ptf ${training}/c_coli.trn`

#Remove paralogous genes from the wgMLST schema
`cd ${out_ccoli}/2_wg_ref_allele/results_*/`
`chewBBACA.py RemoveGenes -i results_alleles.tsv -g RepeatedLoci.txt -o alleleCallMatrix_wg_ref_coli`

#Define cgMLST schema by selecting the loci that are present in the Ref genomes, 95 %, by the use of the TestGenomeQuality
`chewBBACA.py TestGenomeQuality -i alleleCallMatrix_wg_ref_coli.tsv -n 13 -t 200 -s 5
chewBBACA.py ExtractCgMLST -i alleleCallMatrix_wg_ref_coli.tsv -g removedGenomes.txt -o cgMLST_refgenomes -p 0.95`

#Allele calling for target genomes
`chewBBACA.py AlleleCall -i $query_genomes_ccoli -g listgenes_core.txt -o cgMLST_querygenomes --cpu 24 --ptf ${training}/c_coli.trn`

`cd cgMLST_querygenomes/results_*/`
`chewBBACA.py ExtractCgMLST -i results_alleles.tsv -o cgMLST_95 -p 0.95`

Is this the correct way to do it?

The last step produces files cgMLST.tsv and cgMLSTschema.txt. So I guess cgMLST.tsv is the file that goes to Phyloviz program, right?

/adnan

**Comment by rfm-targa** [comment]
Hi @daniazi,

Yes, you should get the 95% cgMLST profile for your samples if you perform that analysis. If the cgMLST.tsv file you get has the cgMLST matrix with the allelic profiles for every query genome, then it is the right file to upload to PHYLOVIZ (please verify that the matrix has no LNF, ASM, ALM, PLOT3, PLOT5 or other special cases, as it is preferable to treat those cases as missing data. Anyway, after the ExtractCgMLST process the matrix should have none of those cases and gene absence is represented as '0', that you can treat as missing data if you wish to.). 

Tell us if you run into any problem or if you need additional information.

**Comment by daniazi** [comment]
Thanks for the reply. I got 1192 genes in the cgmlst.tsv after running last two commands above then I executed: 

`chewBBACA.py TestGenomeQuality -i cgMLST_querygenomes/results_alleles.tsv -n 13 -t 200 -s 5`

I got 1265 genes, the genes should be less for N genomes than N-1 (see figure). In Genes_95%.txt, there were also 1192 genes from 95 to 195. 

<img width="1625" alt="Screenshot 2019-12-06 15 22 42" src="https://user-images.githubusercontent.com/13559060/70329704-47354800-183c-11ea-994c-763077f6a717.png">

For 0s in the cgMLST matrix. Are they by default treated as missing data by Phyloviz or is there a way to mention them?

**Comment by rfm-targa** [comment]
Greetings,

After the last `AlleleCall` process to determine the profiles of your query genomes, you got a `results_alleles.tsv` file with those profiles and gave that file as input to the `ExtractCgMLST` process and to the `TestGenomeQuality` process, but the cgMLST that was extracted had 1192 genes and not 1265 as the `TestGenomeQuality` plot shows, is that right?
You've probably checked this, but I'll ask you to verify that you passed the same `results_alleles.tsv` file to both processes. If that is the case, I would like to know if you can send us the 'results_alleles.tsv' file so that we can reproduce the results and quickly identify the problem. It would help us and we just need that file. If you do not want to share sample IDs you can change them to anything since we only need the matrix with the numbers in each profile.

Regarding the missing data, there should not be any need to define missing data with the type of analysis you're performing.

**Comment by daniazi** [comment]
Hi Rafael,

Yes this is how it was done. Here I attached the results_allele.tsv file produced in the process. Hope it helps.

---
N?r du skickar e-post till SLU s? inneb?r detta att SLU behandlar dina personuppgifter. F?r att l?sa mer om hur detta g?r till, klicka h?r <https://www.slu.se/om-slu/kontakta-slu/personuppgifter/>
E-mailing SLU will result in SLU processing your personal data. For more information on how this is done, click here <https://www.slu.se/en/about-slu/contact-slu/personal-data/>

**Comment by rfm-targa** [comment]
Hi @daniazi,

I cannot download the file that you shared. Can you please send the file to this email:

`rmamede@medicina.ulisboa.pt`

Thank you in advance

**Comment by daniazi** [comment]
Hi @rfm-targa

Have you a got chance to look at the file? I hope you got the file in your mailbox.

Thanks

**Comment by rfm-targa** [comment]
Hi @daniazi,

I have received your file and I'm working through the results to identify any problems. I will let you know more later today, I'm looking into the reasons why the `TestGenomeQuality` is reporting different values for the plot and for the `Genes_95%.txt`.

**Comment by rfm-targa** [comment]
Hi @daniazi,

Sorry for the delay, we have been working on the issue that you reported. It is something that does not happen in every case, but is affecting the results you're getting due to your sample size and the profiles in the matrix. We'll merge some changes that will fix this issue. The value that you get in the results of the `ExtractCgMLST` process and in the `Genes_95%.txt` file from the `TestGenomeQuality` is the correct value. The issue is only related with an incorrect value that appears in the plot.
Thank you for reporting this issue!

**Comment by daniazi** [comment]
Thanks @rfm-targa for solving the issue. 

There is one more thing, whenever the TestGenome has run completely, it waits for the user to press some keys to quit. Due to this commands following this in the bash script never run. I do not know if it happens only on my SGE server.

**Comment by rfm-targa** [comment]
Hey @daniazi,

The script will generally take a noticeable time to finish at the part where the Plotly plot HTML file is created. The HTML file is created with the 'auto_open' option enabled and the HTML file is automatically opened after creation, taking more time if the default Web Browser is not even opened. I do not know if your problem is related with this, but it might be because your script stops at this part where the HTML file is created and automatically opened. The new version will have an argument to control this 'auto_open' option.

All the best,
Rafael

**Comment by daniazi** [comment]
Hi @rfm-targa,

I do not exactly remember the problem but it sounds related. I am closing this issue with the hope that auto-open option will be controllable in the newer version, as you said. 

Thanks for all your help.
