### ISSUE TITLE
Minimum number of genomes?

### ISSUE THREAD

**Issue by nbawe** [B-UMMI/chewBBACA#63]
Hi!

Does the chewBBACA have minimum number of genomes requirement? I was trying to use it to exctract cgMLST between the two isolates but I encountered following error while using `RemoveGenes` `chewBBACA.py: error: the following arguments are required: -i` although `-i` was provided.

**Comment by cimendes** [comment]
Hello! Can you share the command you're using to run chewBBACA? Thanks!

**Comment by nbawe** [comment]
Commands are as follows:
1. `chewBBACA.py CreateSchema -i complete_genomes/ --cpu 3 -o schema_seed --ptf Listeria_monocytogenes.trn`
2. `chewBBACA.py AlleleCall -i complete_genomes/ -g schema_seed/ -o results_cg --cpu 3 --ptf Listeria_monocytogenes.trn`
3. `chewBBACA.py RemoveGenes - i results_cg/results_20200806T163823/results_alleles.tsv -g results_cg/results_20200806T163823/RepeatedLoci.txt -o alleleCallMatrix_cg`

Perhaps it is related to second command as it does not find paralogs?

**Comment by rfm-targa** [comment]
Hi @nbawe! Can you tell me what is the version of the chewBBACA you are using?

**Comment by nbawe** [comment]
Installed using pip3 and version shows `chewBBACA version: 2.5.0`

**Comment by rfm-targa** [comment]
Hello @nbawe!

We have identified the problem in the `RemoveGenes` process and fixed it. We plan to create a new release in `PyPI` and in `Conda` very soon, but for now the fix is only in the repo's master branch. If you really need to run the `RemoveGenes` process you will have to clone and install. However, if you have run `AlleleCall` and it did not find paralogs, you do not need to run `RemoveGenes`. If you want to determine the cgMLST you can simply run the `ExtractCgMLST` process after `AlelleCall`.

Let us know about any other issues or questions!

**Comment by nbawe** [comment]
Thank you! I ran ExtractCgMLST and used PHYLOViZ online to assess the results and everything worked!
@rfm-targa could you please leave the issue open until the new release in PyPI is ready?

One more question:
Is it possible to Extract alignment of all the core genes?

**Comment by nbawe** [comment]
I was testing again and got two following errors with the same 2 genome scheme:
1) Used command:
`chewBBACA.py TestGenomeQuality -i output_cg/cgMLST.tsv -n 13 -t 300 -s 5`

I am really not sure about parameters used if only 2 genomes are compared!

Error:
`Traceback (most recent call last):
  File "/usr/local/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 1487, in main
    functions_info[process][1]()
  File "/usr/local/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 700, in test_schema
    pathOutputfile = args.i
AttributeError: 'Namespace' object has no attribute 'i'`

2) Used command:
`chewBBACA.py SchemaEvaluator -i schema_seed/ -ta 11 -l output.html --cpu 3`

Error:
`Traceback (most recent call last):
  File "/usr/local/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 1487, in main
    functions_info[process][1]()
  File "/usr/local/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 639, in evaluate_schema
    genes = args.i
AttributeError: 'Namespace' object has no attribute 'i'`

**Comment by rfm-targa** [comment]
Hello @nbawe,

We created a new release on PyPI and on Bioconda. You can install the new version (v2.5.4) through `pip` or `conda`. We corrected the problems you encountered in the `RemoveGenes`, `TestGenomeQuality` and `SchemaEvaluator` processes. Those issues started in version 2.5.0. Thank you for pointing them out. Please try to run those processes again and let us know if you encounter any new issue.

The `SchemaEvaluator` process generates a file with a multiple sequence alignment (MSA) for every locus. If you want to have a MSA for each locus that's a way to do it, but if you want a single MSA with all the loci in the core genome you can select the MSA files for the core genes and concatenate the MSAs for all core genes. It is important that you determine that the concatenated MSA is appropriate for your objectives.

There shouldn't be any issue if you only use 2 genomes. The commands for 2 or more genomes have the same structure. One thing that is important is to verify the quality of the genomes you'll provide as input to chewBBACA. Assembly quality is important and you should check that your genomes don't have a high number of contigs, ambiguous bases, high deviations from expected GC content, etc.

Let us know if there is anything else.

**Comment by nbawe** [comment]
Thank you very much everything worked great until SchemaEvaluator. It gives two errors:
1) 
```
'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
[Errno 21] Is a directory: 'schema_seed/short'
[Errno 21] Is a directory: 'schema_seed/profiles_database'
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
'utf-8' codec can't decode byte 0xc5 in position 3: invalid continuation byte
```

2)
`Non-zero return code 126 from 'clustalw2 -infile=rms/genes_html/XXX-protein1113_aligned.fasta -tree', message '/bin/sh: /Users/nbawe/clustalw2: Bad CPU type in executable'`

Thank you for your help

I am using MacOS Catalina zsh.

**Comment by rfm-targa** [comment]
Greetings,

The first errors/warnings should not be a problem. We've added new files to the schema directory in the latest versions and the process is listing them and warning that they are not FASTA files. The process should continue normally after that (future versions will remove those errors/warnings).

The second error is related to MacOS. You are already using zsh, which has been pointed out as a solution for some cases. In your case it might be because clustalw2 is a 32-bit app and MacOS Catalina does not support 32-bit executables. You'll have to use a 64-bit binary to run clustalw2 on your system. I recommend that you uninstall your current clustalw and install/run a new one downloaded from:

http://www.clustal.org/download/current/

If that does not work, I would recommend that you install conda and create a new environment where you can install 64-bit clustalw (it seems to be available in bioconda: https://anaconda.org/bioconda/clustalw/files).

Try this solution and let us know if it fixed the issue.

**Comment by nbawe** [comment]
I can't thank you enough I installed chewBBACA using conda with following command:

`conda create -n chewBBACA_env chewBBACA=2.5.4 clustalw`

1) `CreateSchema` - OK!

2) `AlleleCall` - gives following error while checking dependencies, but finishes OK:
```
Checking dependencies...
Blast installation...True
Prodigal installation...True
Something went wrong. Your blast version is blastp: 2.10.1+
 Package: blast 2.10.1, build Jul 26 2020 02:27:00

Update your blast to 2.5.0 or above. Exited.
```
3) `ExtractCgMLST` - OK!

4) `SchemaEvaluator` - results 2783 total loci, 0 with variability and 2778 with one allele, but the "Allele length, number, loci number and CDS analysis buttons don't show anything is it because of the use of 2 genomes and the results? And also the previously mentioned error appears - but should be OK!

> ```
> 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte
> 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> [Errno 21] Is a directory: 'schema_seed/short'
> [Errno 21] Is a directory: 'schema_seed/profiles_database'
> 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> 'utf-8' codec can't decode byte 0xc5 in position 3: invalid continuation byte
> ```

5) `TestGenomeQuality` - runs OK using default (wiki) values, but as I have 2 genomes all present (95;99;99.5;100%) graphs are excactly the same. Is there something I can do altering parameter or is it due to small number and very similar isolates?

It seems that now I got chewBBACA correctly working. If you could give your opinion on questions rised in 4) SchemaEvaluator and 5) TestGenomeQuality sections I would be very thankful.

Again really appreciate your help.

**Comment by rfm-targa** [comment]
Hello @nbawe, 

The warnings you saw do not affect the results, the processes will simply continue after printing them to the stdout. But we will look into that to update the code and ensure that it properly identifies the BLAST version and that it does not warn about non-FASTA files in `SchemaEvaluator`.

When you use a small number of isolates and they are very similar it is normal that you get those results with `TestGenomeQuality`. You should also verify that they are very similar when you check the `ExtractCgMLST` results.

The `SchemaEvaluator` process needs `MSAViewer` and `Phylocanvas` to fully work. Please verify that you have installed these dependencies. If you have them installed and it still does not show the plots/images, please tell us so that we can look into any issues. Even if it does not show the images, you should find the MSA files in the files created by the process.

We are glad that we have been able to help and thank you for noticing and reporting these issues. Please let us know about anything else.

**Comment by nbawe** [comment]
> The SchemaEvaluator process needs `MSAViewer` and `Phylocanvas` to fully work.

That was the issue - unfortunately I am not able to install them somehow I always get errors while installing using `npm`

**Comment by rfm-targa** [comment]
Hello @nbawe,

We also get errors during the installation but it does seem to install anyway. Can you determine if that is your case?
We are going to change `SchemaEvaluator` and we'll let you know when it is done so that you can try it. It is still important that you manage to install MSAViewer and Phylocanvas.

**Comment by nbawe** [comment]
I can confirm could not install the MSAViewer and Phylocanvas. Please share the commands how did you manage install them. I would be happy to test.

**Comment by rfm-targa** [comment]
I used the following commands:

`npm install msa`
`npm install --save-dev phylocanvas`

These are the commands that are provided in the website of these packages. You probably used the same or equivalent commands. You can share the errors you got and we will try to help you that.

**Comment by nbawe** [comment]
`npm install msa`

Output:
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/nbawe/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/nbawe/package.json'
npm WARN nbawe No description
npm WARN nbawe No repository field.
npm WARN nbawe No README data
npm WARN nbawe No license field.

+ msa@0.0.0
updated 1 package in 3.837s

7 packages are looking for funding
  run `npm fund` for details
```

`npm install --save-dev phylocanvas`

Output:
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/nbawe/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/nbawe/package.json'
npm WARN nbawe No description
npm WARN nbawe No repository field.
npm WARN nbawe No README data
npm WARN nbawe No license field.

+ phylocanvas@2.8.1
updated 1 package and audited 80 packages in 3.878s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



   
   │      New patch version of npm available! 6.14.6 → 6.14.7       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.7   │
   │               Run npm install -g npm to update!                │
```

Mayby it's still due to the fact I have only two genomes?

**Comment by nbawe** [comment]
I mean the fact that no graphs are displayed

**Comment by rfm-targa** [comment]
The problems you have been encountering are not related with the number of genomes.

We have determined that both packages, [MSAViewer](https://msa.biojs.net/) and [Phylocanvas](http://phylocanvas.org/), have installation problems. The problems with MSAViewer are especially difficult to solve because the author has stopped supporting and developing the package. The `SchemaEvaluator` process cannot work properly without those packages.
You can try to install a stable version of each package directly from the source.

We have decided that it is necessary to create a new implementation of the `SchemaEvaluator` process that uses packages that are currently supported and will likely be for a long time. Until then, the `SchemaEvaluator` process will not work properly if users follow the default installation procedures. We will try to find a workaround so that we can post information on how to solve these dependencies problems and offer a solution until the new implementation is out.

For now, we recommend that you try to install those packages from source and verify if that solves the problem in your system.

**Comment by rfm-targa** [comment]
Hello @nbawe,

The latest version, 2.6.0, includes the new implementation of the `SchemaEvaluator` process (@pedrorvc created a new and great implementation!). You can install version 2.6.0 through Pip or Conda and evaluate any external or chewBBACA schema.
You can read more about the new implementation and the information in the final report [here](https://github.com/B-UMMI/chewBBACA/wiki/4.-Schema-Evaluation#evaluate-schema).

I will close this issue, but let us know if there is anything else.
