### ISSUE TITLE
Shorter allele reported as new allele

### ISSUE THREAD

**Issue by valeriaR89** [B-UMMI/chewBBACA#69]
Dear developers,
I'm a beginner with chewBBACA and I realize that AlleleCall reported as new some allele that are just smaller than the one in the scheme of 6 or 9 base out of 400-500 bp.
I have this problem frequently but I thought that there was a sort of lenght tolerance to assign the allele (I run chewBBACA with all default parameteres).
An example of the amount of difference is attached here [allele_differences.txt](https://github.com/B-UMMI/chewBBACA/files/5567798/allele_differences.txt)
Is there a way to assign the existing allele instead of creating a new one?

Thank you for your help!

VR

**Comment by ramirma** [comment]
@valeriaR89 thank you for your interest in chewBBACA.

The issue you bring up has to do with the way chewBBACA identifies what is a locus for the identification of alleles. Please bear in mind that it uses CDSs as identified by Prodigal with an appropriate training file. The allele lmo1236_1 is larger than the called allele by 9 nucleotides. This possibly occurs because there is a) a point mutation in the upstream "TTGGTTATA" region that creates a stop codon or b) for some other reason prodigal has identified the CDS starting at the ATG codon instead of the TTG codon. This behavior by chewBBACA is intended by design. If both the coding sequence and upstream sequence would be the same, prodigal would have identified the same CDS and chewBBACA the same allele.

We therefore believe the two should be different alleles and do not have any option to call these as the same alleles.

I hope I have clarified the issue you raised.

**Comment by valeriaR89** [comment]
Yes, thank you for your answer. 
I'm wondering if in this cases the mode of construction of the assembly may affected the results, even though a very good assembly features. 

Thank you againg for your help.

VR

**Comment by valeriaR89** [comment]
I'm sorry, but I just notice that I found the exact match of the existing allele in my assembly file [my_assembly.txt](https://github.com/B-UMMI/chewBBACA/files/5573237/my_assembly.txt) (attached a part of it). 
What may have happened?

**Comment by ramirma** [comment]
@valeriaR89, it is hard to comment on what may be going on here. Since the coding sequence is the same, option _a)_ that I listed above is obviously not the culprit. We are left with option _b)_ for some reason the ORF prodigal identified in this genome was smaller than the one from the larger allele. chewBBACA relies on prodigal identified ORFs to call alleles so I am really commenting on a dependency and not on chewBBACA's algorithm. What I imagine may have happened is that there are differences in the upstream non-coding sequence that led prodigal to take two different options. Is the contig where this ORF is located really as small as the data you shared? If so, the small size of the contig may have also influenced prodigal's call.

On a more general note. Indeed every allele call, by chewBBACA or any other software, will be heavily influenced by the quality of the assembly (and of the underlying reads of course). I would advise that for a given study all assemblies should be obtained with the same pipeline. There are several high quality assembly pipelines that should produce high quality interchangeable assemblies so this should not really be an issue.

**Comment by valeriaR89** [comment]
> Is the contig where this ORF is located really as small as the data you shared? If so, the small size of the contig may have also influenced prodigal's call.

No, the contig was one of the biggest of the assembly, so I think this is not the problem. 
The only concern is that this happened several times in different samples, and now I understand that it is prodigal which affected the results. 
Thanks anyway for your help and your explanations!
VR

**Comment by ramirma** [comment]
Glad to have helped.

Just a final note to remind you that the calls made by chewBBACA will be consistent on the same assembly, just possibly different from the ones made by other allele callers.
