### ISSUE TITLE
Using a gene list to run a cgMLST from a wgMLST scheme

### ISSUE THREAD

**Issue by dutchscientist** [B-UMMI/chewBBACA#98]
In an older (2.1.0) version of chewBBACA, I used a gene list to call the genes for which the alleles needed to be called. This way I could download a wgMLST scheme (like the Campylobacter one), but ony use the 678-gene cgMLST scheme,

with 2.7.0 and now 2.8.4, it tells me that the freshly downloaded scheme (from Chewie-NS) is an old version, needs to be prepped, and then crashes.

The command line I use is (run from the folder above the cgMLST scheme):
chewBBACA.py AlleleCall -i /home/vetschool/data/training/phylogeny/ -g cjejuni_cgMLST/campy_cgmlst.txt -o /home/vetschool/data/training/cgmlst/ --cpu 2 --ptf cjejuni_cgMLST/Campylobacter_jejuni.trn

When I just run it with the wgMLST scheme, it runs fine, but then it does all the >2700 genes which I don't want, so takes a lot longer:
chewBBACA.py AlleleCall -i /home/vetschool/data/training/phylogeny/ -g cjejuni_cgMLST -o /home/vetschool/data/training/cgmlst/ --cpu 2 --ptf cjejuni_cgMLST/Campylobacter_jejuni.trn

The gene list is just a text file (Unix text, so \n line breaks) with the 678 genes each on a new line:
INNUENDO_wgMLST-024285.fasta
INNUENDO_wgMLST-024286.fasta
INNUENDO_wgMLST-024287.fasta
INNUENDO_wgMLST-024289.fasta
INNUENDO_wgMLST-024294.fasta
etc

Have also tried it from one folder up and add the foldername in front.

Can you tell me what I am doing wrong? Thanks.

**Comment by rfm-targa** [comment]
Hello @dutchscientist,

In the latest version, the gene list has to be passed to the `--gl` parameter. You will have to pass the path to the schema to the `-g` parameter and the path to the file that contains the gene list to the `--gl` parameter (you can run `chewBBACA.py AlleleCall -h` to see the list of parameters, including the `-g` and `--gl` parameters). In your case, the command should be the following:

```
chewBBACA.py AlleleCall -i /home/vetschool/data/training/phylogeny/ -g cjejuni_cgMLST --gl cjejuni_cgMLST/campy_cgmlst.txt -o /home/vetschool/data/training/cgmlst/ --cpu 2
```

I have not included the `--ptf` parameter in the command because the training file should be in the schema and the AlleleCall process will use the training file in the schema by default. In previous versions it was necessary to append the full path to each gene file, but that is no longer necessary. The gene list only needs to contain the identifiers of the genes, with `.fasta` extension (the part of the gene list you have shared is a good example), and the AlleleCall process will locate the files based on the path you pass to the `-g` parameter.

**Comment by dutchscientist** [comment]
Thanks! I had missed the option of doing -h with the AlleleCall switch.

It works, that's excellent :)

**Comment by rfm-targa** [comment]
Glad that it helped!
